spring.application.name=academyfit
spring.datasource.url=jdbc:h2:mem:academyfit
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create
logging.level.org.springframework=INFO
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
# Opcional: Para você ver os erros do SQL no console do IntelliJ
spring.jpa.show-sql=true
#jwt.secret=catalogo21
server.port=8080


